using static System.Net.Mime.MediaTypeNames;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Diagnostics.Metrics;
using System;
namespace Gadevang_Tennis_Klub.Services
{
    public class Secret
    {

        private static string _connectionString = @"";
        public static string ConnectionString
        {
            get
            {
                throw new NotImplementedException();
            }
        }
    }
}
